# Generated by Django 4.1.5 on 2023-01-24 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Gener name')),
            ],
            options={
                'verbose_name': 'Gener',
                'verbose_name_plural': 'Geners',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Language name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Title')),
                ('release_date', models.DateField(verbose_name='Release_Date')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('gener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.gener', verbose_name='Gener')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
