# Generated by Django 4.1.5 on 2023-01-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Title')),
                ('release_date', models.DateField(verbose_name='Release_Date')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('gener', models.CharField(max_length=80, verbose_name='Gener name')),
                ('language', models.CharField(max_length=80, verbose_name='Language name')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='MoviePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Title')),
                ('created_date', models.TimeField(auto_now_add=True, verbose_name='Created')),
                ('public', models.BooleanField(default=True)),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('movies', models.ManyToManyField(related_name='playlists', to='movies.movie')),
            ],
            options={
                'verbose_name': 'MoviePlaylist',
                'verbose_name_plural': 'MoviePlaylists',
            },
        ),
    ]
